/**
 * Service de génération automatique de rapports hebdomadaires avec IA
 * 
 * Ce service analyse les tâches de la semaine et génère automatiquement
 * le contenu des rapports en utilisant l'IA.
 */

import { supabase } from './supabaseClient'

/**
 * Génère un rapport hebdomadaire automatiquement à partir des tâches
 * @param {string} userId - ID de l'utilisateur
 * @param {Date} weekStart - Date de début de la semaine
 * @returns {Promise<Object>} Rapport généré avec contenu IA
 */
export async function generateWeeklyReportWithAI(userId, weekStart) {
  try {
    console.log('🤖 Génération automatique du rapport pour la semaine:', weekStart)
    
    // 1. Récupérer toutes les tâches de la semaine pour cet utilisateur
    const weekEnd = new Date(weekStart)
    weekEnd.setDate(weekEnd.getDate() + 6)
    weekEnd.setHours(23, 59, 59, 999)

    // Récupérer les tâches assignées à cet utilisateur
    // qui ont été créées, modifiées ou avec date limite dans la semaine
    const { data: allTasks, error: tasksError } = await supabase
      .from('tasks')
      .select('*')
      .eq('assigned_to', userId)
      .order('created_at', { ascending: true })

    if (tasksError) {
      console.error('❌ Erreur lors de la récupération des tâches:', tasksError)
      throw tasksError
    }

    // Filtrer les tâches pour la semaine (côté client car Supabase .or() est complexe)
    const tasks = (allTasks || []).filter(task => {
      const created = new Date(task.created_at)
      const dueDate = task.due_date ? new Date(task.due_date) : null
      const updated = task.updated_at ? new Date(task.updated_at) : null

      return (
        (created >= weekStart && created <= weekEnd) ||
        (dueDate && dueDate >= weekStart && dueDate <= weekEnd) ||
        (updated && updated >= weekStart && updated <= weekEnd)
      )
    })

    console.log('📋 Tâches trouvées pour la semaine:', tasks?.length || 0)

    // 2. Calculer les statistiques
    const stats = calculateTaskStatistics(tasks || [])
    
    // 3. Générer le contenu avec l'IA (ou logique intelligente)
    const aiContent = await generateReportContent(tasks || [], stats, weekStart, weekEnd)
    
    // 4. Extraire les IDs des tâches
    const taskIds = (tasks || []).map(t => t.id)

    return {
      taskIds,
      taskStatistics: stats,
      aiGeneratedContent: aiContent,
      sections: {
        objectifs: aiContent.objectifs || generateObjectivesFromTasks(tasks || []),
        realisations: aiContent.realisations || generateRealisationsFromTasks(tasks || []),
        difficultes: aiContent.difficultes || generateDifficultesFromTasks(tasks || []),
        solutions: aiContent.solutions || generateSolutionsFromTasks(tasks || []),
        besoins: aiContent.besoins || generateBesoinsFromTasks(tasks || []),
        perspectives: aiContent.perspectives || generatePerspectivesFromTasks(tasks || []),
      },
      autoGenerated: true,
    }
  } catch (error) {
    console.error('❌ Erreur lors de la génération du rapport:', error)
    throw error
  }
}

/**
 * Calcule les statistiques des tâches
 */
function calculateTaskStatistics(tasks) {
  const stats = {
    total: tasks.length,
    planifie: tasks.filter(t => t.status === 'planifie').length,
    en_cours: tasks.filter(t => t.status === 'en_cours').length,
    termine: tasks.filter(t => t.status === 'termine').length,
    en_retard: tasks.filter(t => t.status === 'en_retard').length,
    haute_priorite: tasks.filter(t => t.priority === 'haute').length,
    moyenne_priorite: tasks.filter(t => t.priority === 'moyenne').length,
    basse_priorite: tasks.filter(t => t.priority === 'basse').length,
    taches_list: tasks.map(t => ({
      id: t.id,
      title: t.title,
      status: t.status,
      priority: t.priority,
      due_date: t.due_date,
      created_at: t.created_at,
    })),
  }
  
  return stats
}

/**
 * Génère le contenu du rapport avec l'IA
 * Pour l'instant, utilise une logique intelligente basée sur les tâches
 * Peut être étendu avec OpenAI API ou autre service IA
 */
async function generateReportContent(tasks, stats, weekStart, weekEnd) {
  // Logique intelligente de génération basée sur les tâches
  // Peut être remplacée par un appel à OpenAI API
  
  const objectifs = generateObjectivesFromTasks(tasks)
  const realisations = generateRealisationsFromTasks(tasks)
  const difficultes = generateDifficultesFromTasks(tasks)
  const solutions = generateSolutionsFromTasks(tasks)
  const besoins = generateBesoinsFromTasks(tasks)
  const perspectives = generatePerspectivesFromTasks(tasks)

  return {
    objectifs,
    realisations,
    difficultes,
    solutions,
    besoins,
    perspectives,
    generated_at: new Date().toISOString(),
    method: 'intelligent_analysis', // ou 'openai' si on utilise OpenAI
  }
}

/**
 * Génère la section "Objectifs" à partir des tâches
 */
function generateObjectivesFromTasks(tasks) {
  if (tasks.length === 0) {
    return 'Aucune tâche assignée cette semaine.'
  }

  const plannedTasks = tasks.filter(t => t.status === 'planifie' || t.status === 'en_cours')
  
  if (plannedTasks.length === 0) {
    return 'Toutes les tâches prévues ont été complétées.'
  }

  const objectives = plannedTasks
    .map(t => `- ${t.title} (Priorité: ${t.priority === 'haute' ? 'Haute' : t.priority === 'moyenne' ? 'Moyenne' : 'Basse'})`)
    .join('\n')

  return `Objectifs de la semaine basés sur les tâches assignées :\n\n${objectives}`
}

/**
 * Génère la section "Réalisations" à partir des tâches terminées
 */
function generateRealisationsFromTasks(tasks) {
  const completedTasks = tasks.filter(t => t.status === 'termine')
  
  if (completedTasks.length === 0) {
    return 'Aucune tâche terminée cette semaine.'
  }

  const realisations = completedTasks
    .map(t => `- ${t.title}${t.description ? ` : ${t.description.substring(0, 100)}...` : ''}`)
    .join('\n')

  return `Réalisations de la semaine :\n\n${realisations}\n\nTotal : ${completedTasks.length} tâche(s) terminée(s).`
}

/**
 * Génère la section "Difficultés" à partir des tâches en retard
 */
function generateDifficultesFromTasks(tasks) {
  const delayedTasks = tasks.filter(t => t.status === 'en_retard')
  const overdueTasks = tasks.filter(t => {
    if (!t.due_date) return false
    const dueDate = new Date(t.due_date)
    return dueDate < new Date() && t.status !== 'termine'
  })

  const allDifficulties = [...delayedTasks, ...overdueTasks.filter(t => !delayedTasks.find(dt => dt.id === t.id))]

  if (allDifficulties.length === 0) {
    return 'Aucune difficulté majeure rencontrée cette semaine.'
  }

  const difficultes = allDifficulties
    .map(t => {
      const dueDate = t.due_date ? new Date(t.due_date).toLocaleDateString('fr-FR') : 'Non définie'
      return `- ${t.title} : Date limite dépassée (${dueDate})`
    })
    .join('\n')

  return `Difficultés rencontrées :\n\n${difficultes}`
}

/**
 * Génère la section "Solutions" à partir des tâches en cours
 */
function generateSolutionsFromTasks(tasks) {
  const inProgressTasks = tasks.filter(t => t.status === 'en_cours')
  
  if (inProgressTasks.length === 0) {
    return 'Aucune activité en cours de réalisation.'
  }

  const solutions = inProgressTasks
    .map(t => `- ${t.title} : En cours de traitement`)
    .join('\n')

  return `Activités en cours de réalisation :\n\n${solutions}`
}

/**
 * Génère la section "Besoins" basée sur les tâches à haute priorité non terminées
 */
function generateBesoinsFromTasks(tasks) {
  const highPriorityPending = tasks.filter(t => 
    t.priority === 'haute' && 
    (t.status === 'planifie' || t.status === 'en_cours' || t.status === 'en_retard')
  )

  if (highPriorityPending.length === 0) {
    return 'Aucun besoin particulier identifié cette semaine.'
  }

  const besoins = highPriorityPending
    .map(t => `- ${t.title} : Nécessite une attention prioritaire`)
    .join('\n')

  return `Besoins identifiés :\n\n${besoins}`
}

/**
 * Génère la section "Perspectives" basée sur les tâches planifiées
 */
function generatePerspectivesFromTasks(tasks) {
  const plannedTasks = tasks.filter(t => t.status === 'planifie')
  const upcomingTasks = tasks.filter(t => {
    if (!t.due_date) return false
    const dueDate = new Date(t.due_date)
    const nextWeek = new Date()
    nextWeek.setDate(nextWeek.getDate() + 7)
    return dueDate <= nextWeek && t.status !== 'termine'
  })

  if (plannedTasks.length === 0 && upcomingTasks.length === 0) {
    return 'Aucune perspective particulière pour la semaine prochaine.'
  }

  const perspectives = [
    ...plannedTasks.map(t => `- ${t.title} : À planifier pour la semaine prochaine`),
    ...upcomingTasks.filter(t => !plannedTasks.find(pt => pt.id === t.id))
      .map(t => `- ${t.title} : Échéance prévue pour ${new Date(t.due_date).toLocaleDateString('fr-FR')}`)
  ].join('\n')

  return `Perspectives pour la semaine prochaine :\n\n${perspectives}`
}

/**
 * Améliore et réécrit le rapport avec l'IA pour une rédaction professionnelle
 * @param {Object} reportData - Données du rapport (sections)
 * @returns {Promise<Object>} Rapport amélioré avec texte bien rédigé
 */
export async function improveReportWithAI(reportData) {
  try {
    console.log('🤖 Amélioration du rapport avec l\'IA...')
    
    const improvedSections = {}
    const sections = reportData.sections || {}
    
    // Améliorer chaque section avec une rédaction professionnelle
    const sectionKeys = Object.keys(sections)
    for (let i = 0; i < sectionKeys.length; i++) {
      const key = sectionKeys[i]
      const value = sections[key]
      if (value && typeof value === 'string' && value.trim().length > 0) {
        improvedSections[key] = await improveSectionText(key, value)
      } else {
        improvedSections[key] = value || ''
      }
    }
    
    console.log('✅ Rapport amélioré avec succès')
    
    return {
      ...reportData,
      sections: improvedSections,
      improved: true,
      improvedAt: new Date().toISOString(),
    }
  } catch (error) {
    console.error('❌ Erreur lors de l\'amélioration du rapport:', error)
    throw error
  }
}

/**
 * Améliore le texte d'une section avec une rédaction professionnelle
 */
async function improveSectionText(sectionKey, originalText) {
  // Mapping des sections vers leurs titres formels
  const sectionTitles = {
    objectifs: 'Objectifs de la semaine',
    realisations: 'Réalisations',
    difficultes: 'Difficultés rencontrées',
    solutions: 'Solutions apportées',
    besoins: 'Besoins identifiés',
    perspectives: 'Perspectives pour la semaine prochaine',
  }
  
  const sectionTitle = sectionTitles[sectionKey] || sectionKey
  
  // Logique intelligente de réécriture
  let improvedText = originalText
  
  // 1. Nettoyer et structurer le texte
  improvedText = cleanAndStructureText(improvedText)
  
  // 2. Améliorer la formulation selon le type de section
  switch (sectionKey) {
    case 'objectifs':
      improvedText = improveObjectivesText(improvedText)
      break
    case 'realisations':
      improvedText = improveRealisationsText(improvedText)
      break
    case 'difficultes':
      improvedText = improveDifficultesText(improvedText)
      break
    case 'solutions':
      improvedText = improveSolutionsText(improvedText)
      break
    case 'besoins':
      improvedText = improveBesoinsText(improvedText)
      break
    case 'perspectives':
      improvedText = improvePerspectivesText(improvedText)
      break
  }
  
  // 3. Ajouter une introduction professionnelle si nécessaire
  if (!improvedText.startsWith('Durant cette semaine') && !improvedText.startsWith('Cette semaine')) {
    improvedText = addProfessionalIntroduction(sectionKey, improvedText)
  }
  
  return improvedText
}

/**
 * Nettoie et structure le texte
 */
function cleanAndStructureText(text) {
  // Supprimer les emojis et caractères spéciaux
  let cleaned = text.replace(/[✅⚠️💡📦🚀]/g, '')
  
  // Remplacer les tirets par des puces si nécessaire
  cleaned = cleaned.replace(/^-\s*/gm, '• ')
  
  // Supprimer les espaces multiples
  cleaned = cleaned.replace(/\s+/g, ' ')
  
  // Capitaliser la première lettre
  cleaned = cleaned.trim()
  if (cleaned.length > 0) {
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
  }
  
  return cleaned
}

/**
 * Améliore le texte des objectifs
 */
function improveObjectivesText(text) {
  let improved = text
  
  // Ajouter des formulations professionnelles
  if (!improved.includes('objectif') && !improved.includes('Objectif')) {
    improved = `Les objectifs fixés pour cette semaine étaient les suivants : ${improved.toLowerCase()}`
  }
  
  // Structurer en paragraphe cohérent
  improved = improved.replace(/\n/g, ' ')
  improved = improved.replace(/\s+/g, ' ')
  
  return improved
}

/**
 * Améliore le texte des réalisations
 */
function improveRealisationsText(text) {
  let improved = text
  
  // Transformer en phrases complètes
  const lines = improved.split('\n').filter(line => line.trim().length > 0)
  
  if (lines.length > 1) {
    // Si plusieurs lignes, créer un paragraphe structuré
    improved = `Durant cette semaine, j'ai pu accomplir les réalisations suivantes :\n\n`
    improved += lines.map(line => {
      let cleanLine = line.replace(/^[•\-\s]+/, '').trim()
      if (!cleanLine.endsWith('.')) cleanLine += '.'
      return `• ${cleanLine}`
    }).join('\n')
  } else {
    // Une seule ligne, améliorer la formulation
    if (!improved.includes('réalisé') && !improved.includes('accompli') && !improved.includes('terminé')) {
      improved = `J'ai réalisé les activités suivantes : ${improved.toLowerCase()}`
    }
  }
  
  return improved
}

/**
 * Améliore le texte des difficultés
 */
function improveDifficultesText(text) {
  let improved = text
  
  // Ajouter un ton professionnel
  if (!improved.includes('rencontré') && !improved.includes('difficulté')) {
    improved = `J'ai rencontré les difficultés suivantes : ${improved.toLowerCase()}`
  }
  
  // Structurer en phrases complètes
  improved = improved.replace(/\n/g, ' ')
  improved = improved.replace(/\s+/g, ' ')
  
  return improved
}

/**
 * Améliore le texte des solutions
 */
function improveSolutionsText(text) {
  let improved = text
  
  // Ajouter des formulations professionnelles
  if (!improved.includes('solution') && !improved.includes('mis en place')) {
    improved = `Pour résoudre ces difficultés, j'ai mis en place les solutions suivantes : ${improved.toLowerCase()}`
  }
  
  // Structurer en paragraphe
  improved = improved.replace(/\n/g, ' ')
  improved = improved.replace(/\s+/g, ' ')
  
  return improved
}

/**
 * Améliore le texte des besoins
 */
function improveBesoinsText(text) {
  let improved = text
  
  // Ajouter une introduction professionnelle
  if (!improved.includes('besoin') && !improved.includes('nécessaire')) {
    improved = `Les besoins identifiés pour améliorer mon travail sont les suivants : ${improved.toLowerCase()}`
  }
  
  // Structurer en liste si nécessaire
  const lines = improved.split('\n').filter(line => line.trim().length > 0)
  if (lines.length > 1) {
    improved = lines.map(line => {
      let cleanLine = line.replace(/^[•\-\s]+/, '').trim()
      if (!cleanLine.endsWith('.')) cleanLine += '.'
      return `• ${cleanLine}`
    }).join('\n')
  }
  
  return improved
}

/**
 * Améliore le texte des perspectives
 */
function improvePerspectivesText(text) {
  let improved = text
  
  // Ajouter une introduction professionnelle
  if (!improved.includes('perspective') && !improved.includes('prochaine')) {
    improved = `Pour la semaine prochaine, mes perspectives sont les suivantes : ${improved.toLowerCase()}`
  }
  
  // Structurer en paragraphe cohérent
  improved = improved.replace(/\n/g, ' ')
  improved = improved.replace(/\s+/g, ' ')
  
  return improved
}

/**
 * Ajoute une introduction professionnelle à la section
 */
function addProfessionalIntroduction(sectionKey, text) {
  const introductions = {
    objectifs: 'Durant cette semaine, les objectifs que je m\'étais fixés étaient les suivants :',
    realisations: 'Durant cette semaine, j\'ai pu accomplir les réalisations suivantes :',
    difficultes: 'Au cours de cette semaine, j\'ai rencontré les difficultés suivantes :',
    solutions: 'Pour faire face à ces difficultés, j\'ai mis en place les solutions suivantes :',
    besoins: 'Afin d\'améliorer mon efficacité, j\'ai identifié les besoins suivants :',
    perspectives: 'Pour la semaine prochaine, mes perspectives sont les suivantes :',
  }
  
  const intro = introductions[sectionKey]
  if (intro && !text.toLowerCase().includes(intro.toLowerCase().substring(0, 20))) {
    return `${intro}\n\n${text}`
  }
  
  return text
}

/**
 * Envoie automatiquement le rapport au directeur concerné (celui de la direction de l'expéditeur)
 */
export async function sendReportToDirectrice(reportId) {
  try {
    const { directionsService } = await import('./api.js')

    // Récupérer le rapport
    const { data: report } = await supabase
      .from('reports')
      .select('*')
      .eq('id', reportId)
      .single()

    if (!report) {
      throw new Error('Rapport non trouvé')
    }

    // Trouver le directeur de la direction de l'expéditeur (report.direction = nom du service)
    let directorId = await directionsService.getDirectorIdForService(report.direction)
    if (!directorId) {
      directorId = await directionsService.getDirectorIdForUserId(report.user_id)
    }
    if (!directorId) {
      // Fallback : premier directeur trouvé (rétrocompatibilité)
      const { data: fallback } = await supabase.from('users').select('id').eq('role', 'directrice').limit(1).maybeSingle()
      directorId = fallback?.id
    }
    if (!directorId) {
      throw new Error('Directeur/directrice non trouvé(e) pour cette direction')
    }

    // Créer une notification pour le directeur concerné
    const { data: notification, error } = await supabase
      .from('notifications')
      .insert({
        user_id: directorId,
        title: 'Nouveau rapport hebdomadaire',
        message: `${report.user_name} a envoyé son rapport hebdomadaire pour la semaine du ${new Date(report.week).toLocaleDateString('fr-FR')}`,
        type: 'info',
        read: false,
        metadata: JSON.stringify({
          report_id: reportId,
          user_id: report.user_id,
          week: report.week,
        }),
      })
      .select()
      .single()

    if (error) {
      console.error('❌ Erreur lors de la création de la notification:', error)
      throw error
    }

    console.log('✅ Notification envoyée au directeur concerné pour le rapport:', reportId)
    return notification
  } catch (error) {
    console.error('❌ Erreur lors de l\'envoi du rapport au directeur:', error)
    throw error
  }
}

